### ISSUE TITLE
Doesn't seem to work in  Craft 2.6

### ISSUE THREAD

**Issue by jcdarwin** [mildlygeeky/craft_kint#5]
I saw the note the this plugin was aimed at Craft 2.4 / 2.5, and as I should have know might happen, when I installed it under Craft 2.6.2784, it didn't appear in the plugins panel, so I guess it's not compatible with Craft 2.6.

Would you consider upgrading this plugin such that it does work with Craft 2.6?

**Comment by mildlygeeky** [comment]
Hey @jcdarwin — it certainly works in 2.6 (just tested). You likely just need to extract the interior folder "kint", instead of just putting the entire folder into your plugins folder.

I've been considering making my plugins just be the entire folder (rather than a folder inside the repo, a la ExpressionEngine plugins), and will mark it as a new major version if I do.

**Comment by jcdarwin** [comment]
That's great -- thanks Patrick.

Yes, my fault for not reading the instructions closely enough -- if you
were to make your plugin be just the entire folder, that would probably be
helpful to others too -- also maybe a note in the README that it works with
2.6?

Thanks again,

Jason
